---

- hosts: localhost
  tasks: 
    - name: get the username running the deploy
      command: whoami
      register: username

    - block:
      - include_role:
          name: setup
      become: yes
    
