---


- name: check configuration
  command: nginx -t -c /etc/nginx/nginx.conf
  register: _app_nginx_conf_check
  changed_when: "_app_nginx_conf_check.rc != 0"

- name: reload nginx
  service:
    name: nginx
    state: reloaded
