---


- name: check configuration
  command: nginx -t -c /etc/nginx/nginx.conf
  register: conf_check
  changed_when: "conf_check.rc != 0"
  become: yes

- name: reload nginx
  service:
    name: nginx
    state: reloaded
  become: yes
