---

- name: docker prerequisite
  apt:
    pkg:
    - nginx
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release



- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present



- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present



- name: install docker
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'docker-ce', 'docker-ce-cli', 'containerd.io']


- name: adding '{{ ansible_env.USER }}' to group docker
  user:
    name: '{{ ansible_env.USER }}'
    groups: docker
    append: yes


- name: Install Docker Module for Python
  pip:
    name: docker-py
  become: no


- name: Install nginx
  apt:
    name: ['nginx']
    state: latest



- name: Allow all access to tcp port 80
  ufw:
    rule: allow
    port: '80'
    proto: tcp
